### PR TITLE
Add flutter_lints, format the code

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by victoreronmosele** [comment]
Hi @domesticmouse, thanks for submitting the PR. 
I'll take a look, shortly.

**Comment by victoreronmosele** [comment]
I've been trying to figure out why the Github Action workflow was skipped for this PR.

**Comment by victoreronmosele** [comment]
It's with this line in the workflow file:

https://github.com/victoreronmosele/flutter_gradient_generator/blob/cac1e93703b168a0aaaa64164c0690e5c0dfc3c6/.github/workflows/firebase-hosting-pull-request.yml#L8

I'll remove it so PRs from forks can trigger the workflow.

**Comment by victoreronmosele** [comment]
Hi @domesticmouse, could you pull my `develop` branch into yours so it has the change from PR #45 where the restriction from workflows for forks is removed?

**Comment by domesticmouse** [comment]
Done and done. You'll need to auth the CI run =)

**Comment by domesticmouse** [comment]
I’ve got no idea how to fix the CI failure

**Comment by victoreronmosele** [comment]
It has to do with the fork not having access to the secret:
https://github.com/victoreronmosele/flutter_gradient_generator/blob/677cee1bf21a798f14621786671e9bc3e8a897a6/.github/workflows/firebase-hosting-pull-request.yml#L25

Trying to look for a way around this.

**Comment by victoreronmosele** [comment]
I'll most likely revert #45 so the preview deployment is skipped for forks and just add `flutter test` to the workflow.

**Comment by domesticmouse** [comment]
Merged upstream, please re-auth the workflow

**Review by victoreronmosele — APPROVED** [review]

**Pull request merged**
